name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: bundle install
        run: bundle install
      - name: Run tests
        run: rails test
